import hashlib
import inspect
import json
import subprocess
import sys
import tempfile
import unittest
from collections import Counter
from pathlib import Path

from formulaguard.a1 import parse_address
from formulaguard.formula import formula_fingerprint, normalized_formula
from formulaguard.workbook import WorkbookModel
from scripts import freeze_v5_core, run_v5_core_predictions, run_v5_core_stage
from scripts import audit_v5_core_public_inputs
from scripts import (
    audit_v5_core_validation,
    lock_v5_core_blind,
    prepare_v5_core_third_party_pack,
    score_v5_core_blind,
    train_v5_core_ranker,
)
from scripts.score_v5_core_predictions import hash_file, verify_prediction_completion
from scripts.audit_v5_core_dataset import audit_root
from scripts.build_v5_core_dataset import (
    PROFILE_COUNTS,
    build_case,
    clean_cases,
    clean_control_partition,
    enumerate_cases,
    write_xlsx,
)


class V5CoreProtocolTests(unittest.TestCase):
    def test_preregistered_internal_counts_are_exact(self):
        for profile in ("smoke", "pilot", "development", "redteam", "validation", "third_party"):
            self.assertEqual(len(enumerate_cases(profile)), PROFILE_COUNTS[profile])
        self.assertEqual(len(clean_cases()), 360)

    def test_redteam_factorial_covers_every_regime_and_ambiguity(self):
        cases = enumerate_cases("redteam")
        factorial = Counter((case.error_type, case.topology, case.regime) for case in cases)
        self.assertEqual(len(factorial), 6 * 5 * 4)
        self.assertEqual(set(factorial.values()), {3})
        self.assertEqual(
            Counter(case.ambiguity for case in cases),
            Counter({
                "competing_family": 120,
                "legitimate_summary": 120,
                "near_tie": 120,
            }),
        )
        self.assertEqual(set(Counter(case.regime for case in cases).values()), {90})

    def test_project_builder_refuses_to_create_its_own_independent_final_set(self):
        source = inspect.getsource(__import__(
            "scripts.build_v5_core_dataset", fromlist=["main"],
        ).main)
        self.assertIn('if args.profile == "third_party"', source)
        self.assertIn("cannot be generated by the project", source)

    def test_clean_calibration_and_locked_controls_are_balanced(self):
        cases = clean_cases()
        for limit, per_structure in ((24, 2), (48, 4), (240, 20)):
            self.assertEqual(Counter(case.ambiguity for case in cases[:limit]), Counter({
                structure: per_structure for structure in {case.ambiguity for case in cases}
            }))
        self.assertTrue(all(clean_control_partition(case) == "calibration" for case in cases[:240]))
        self.assertTrue(all(clean_control_partition(case) == "locked_control" for case in cases[240:]))
        self.assertEqual(set(Counter(case.ambiguity for case in cases[240:]).values()), {10})

    def test_labeled_formula_pairs_are_disjoint_across_splits(self):
        pairs = {}
        for profile in ("pilot", "development", "redteam", "validation", "third_party"):
            pairs[profile] = {
                (normalized_formula(build_case(case)[2]), normalized_formula(build_case(case)[3]))
                for case in enumerate_cases(profile)
            }
        profiles = list(pairs)
        for index, left in enumerate(profiles):
            for right in profiles[index + 1:]:
                    self.assertFalse(pairs[left] & pairs[right], (left, right))

    def test_dataset_audit_proves_single_injection_original_and_sink_change(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "smoke"
            subprocess.check_call(
                [
                    sys.executable,
                    str(Path(__file__).resolve().parents[1] / "scripts/build_v5_core_dataset.py"),
                    "--profile", "smoke", "--limit", "1", "--output", str(root),
                ],
                stdout=subprocess.DEVNULL,
            )
            audit, _, _ = audit_root(root)
            self.assertTrue(audit["hard_gate_passed"], audit["reasons"])
            public_row = json.loads((root / "instances.jsonl").read_text(encoding="utf-8"))
            labels_path = root / "evaluation_labels.jsonl"
            label = json.loads(labels_path.read_text(encoding="utf-8"))
            mutant, original, non_neighbor = prepare_v5_core_third_party_pack.validate_pair(
                root, public_row, label,
            )
            self.assertTrue(mutant.is_file())
            self.assertTrue(original.is_file())
            self.assertIsInstance(non_neighbor, bool)
            label["correct_formula"] = "=1+1"
            labels_path.write_text(json.dumps(label) + "\n", encoding="utf-8")
            tampered, _, _ = audit_root(root)
            self.assertFalse(tampered["hard_gate_passed"])
            self.assertTrue(any(
                "changed build artifact" in reason or "correct formula disagrees" in reason
                for reason in tampered["reasons"]
            ))

    def test_clean_structure_probes_are_real_and_pairwise_distinct(self):
        selected = {}
        for case in clean_cases():
            selected.setdefault(case.ambiguity, case)
        self.assertEqual(len(selected), 12)
        signatures = {}
        with tempfile.TemporaryDirectory() as directory:
            for structure, case in selected.items():
                path = Path(directory) / f"{structure}.xlsx"
                sheets, *_ = build_case(case, clean_only=True)
                write_xlsx(path, sheets)
                model = WorkbookModel.from_xlsx(path)
                _, errors = model.evaluate()
                self.assertFalse(errors, structure)
                probe = []
                for (sheet, address), formula in model.formulas.items():
                    parsed = parse_address(address)
                    if sheet == "Model" and 23 <= parsed.col <= 28:
                        probe.append((parsed.row, parsed.col, formula_fingerprint(formula, address)))
                self.assertTrue(probe, structure)
                min_row = min(item[0] for item in probe)
                min_col = min(item[1] for item in probe)
                normalized = sorted((row - min_row, col - min_col, fp) for row, col, fp in probe)
                signatures[structure] = hashlib.sha256(json.dumps(normalized).encode("utf-8")).hexdigest()
        self.assertEqual(len(set(signatures.values())), 12, signatures)

    def test_prediction_worker_source_cannot_read_labels(self):
        source = inspect.getsource(run_v5_core_predictions)
        self.assertNotIn("evaluation_labels", source)
        self.assertNotIn("correct_formula", source)
        self.assertNotIn("source_cell", source)

    def test_public_prediction_metadata_declares_empty_label_reads(self):
        source = inspect.getsource(run_v5_core_predictions.main)
        self.assertIn('"label_files_read": []', source)

    def test_locked_validation_uses_public_audit_before_scoring(self):
        public_source = inspect.getsource(audit_v5_core_public_inputs)
        self.assertNotIn("evaluation_labels", public_source)
        self.assertNotIn("correct_formula", public_source)
        stage_source = inspect.getsource(run_v5_core_stage.main)
        lock_branch, score_branch = stage_source.split(
            'if not (root / "prediction_lock.json").exists()', 1,
        )
        self.assertIn("audit_v5_core_public_inputs.py", lock_branch)
        self.assertNotIn("audit_v5_core_dataset.py", lock_branch.rsplit('if args.stage == "validation_lock":', 1)[1])
        self.assertIn("audit_v5_core_dataset.py", score_branch)
        self.assertIn("locked input changed", score_branch)

    def test_smoke_and_pilot_audit_real_data_before_prediction(self):
        source = inspect.getsource(run_v5_core_stage.main)
        smoke_branch = source.split('if args.stage == "smoke":', 1)[1].split(
            'if args.stage == "pilot":', 1,
        )[0]
        pilot_branch = source.split('if args.stage == "pilot":', 1)[1].split(
            'development = Path(', 1,
        )[0]
        for branch in (smoke_branch, pilot_branch):
            self.assertLess(
                branch.index("audit_v5_core_dataset.py"),
                branch.index("raw_predictions"),
            )

    def test_scorer_detects_post_completion_shard_tampering(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "shards").mkdir()
            metadata = root / "prediction_metadata.json"
            metadata.write_text(json.dumps({"label_files_read": []}), encoding="utf-8")
            shard = root / "shards/case.json"
            shard.write_text(json.dumps({"instance_id": "case"}), encoding="utf-8")
            digest = hashlib.sha256()
            digest.update(shard.name.encode("utf-8"))
            digest.update(bytes.fromhex(hash_file(shard)))
            (root / "prediction_complete.json").write_text(json.dumps({
                "instances": 1,
                "metadata_sha256": hash_file(metadata),
                "combined_shards_sha256": digest.hexdigest(),
            }), encoding="utf-8")
            verify_prediction_completion(root)
            shard.write_text(json.dumps({"instance_id": "changed"}), encoding="utf-8")
            with self.assertRaises(SystemExit):
                verify_prediction_completion(root)

    def test_freeze_receipt_locks_code_data_evidence_and_environment(self):
        source = inspect.getsource(freeze_v5_core.main)
        for required_field in (
            '"source_sha256"',
            '"historical_source_sha256"',
            '"data_manifest_sha256"',
            '"evidence_sha256"',
            '"environment"',
            '"post_validation_retuning_allowed": False',
        ):
            self.assertIn(required_field, source)
        self.assertIn('git("status", "--porcelain")', source)
        self.assertIn('selection.get("no_parameter_changes_after_this_receipt")', source)
        self.assertLess(source.index("missing_prerequisites"), source.index("json.loads(selection_path"))

    def test_freeze_manifest_keys_are_repository_relative_and_portable(self):
        self.assertEqual(
            freeze_v5_core.manifest_key(Path("results/v5_core_validation/summary.json")),
            "results/v5_core_validation/summary.json",
        )

    def test_learned_head_records_reproducibility_and_family_stability(self):
        training_source = inspect.getsource(train_v5_core_ranker.main)
        for field in (
            '"training_manifest_hash"',
            '"source_code_hash"',
            '"git_commit"',
            '"feature_scaler"',
            '"cross_validation_results"',
            '"held_out_family_pair_accuracy"',
        ):
            self.assertIn(field, training_source)
        gate_source = inspect.getsource(audit_v5_core_validation.main)
        self.assertIn('training.get("major_feature_directions_consistent"', gate_source)
        self.assertIn('training.get("held_out_family_success_fraction"', gate_source)
        self.assertIn('training.get("worst_held_out_family_pair_accuracy"', gate_source)

    def test_template_group_folds_are_deterministic_and_balanced(self):
        families = [f"family_{index:03d}" for index in range(200)]
        mapping = train_v5_core_ranker.assign_template_folds(reversed(families))
        self.assertEqual(set(Counter(mapping.values()).values()), {40})
        self.assertEqual(mapping, train_v5_core_ranker.assign_template_folds(families))

    def test_third_party_lock_verifies_precommit_tag_and_both_primary_cis(self):
        lock_source = inspect.getsource(lock_v5_core_blind.main)
        self.assertIn('precommit.get("public_zip_sha256")', lock_source)
        self.assertIn("tagged_freeze_bytes()", lock_source)
        self.assertIn('"third_party_precommit_sha256"', lock_source)
        score_source = inspect.getsource(score_v5_core_blind.main)
        self.assertIn('"macro_top5_ci95"', score_source)
        self.assertIn('"mrr_ci95"', score_source)
        self.assertIn('"candidate_coverage_32"', score_source)
        prepare_source = inspect.getsource(prepare_v5_core_third_party_pack.main)
        self.assertIn("prepared_by_independent_person", prepare_source)
        self.assertIn("validate_pair(input_root", prepare_source)
        self.assertIn("outside the project repository", prepare_source)
        self.assertEqual(
            freeze_v5_core.manifest_key(
                Path("D:/code/QCT/results/v5_core_validation/summary.json")
            ),
            "results/v5_core_validation/summary.json",
        )


if __name__ == "__main__":
    unittest.main()
